version: '3.8'

services:
  metsenat-api:
    image: metsenat-api
    depends_on:
      - "metsenat-db"
    container_name: metsenat-api
    ports:
      - "8080:80"
    build:
      context: .
      dockerfile: .
    networks:
      - dev

  metsenat-db:
    image: postgres:latest
    container_name: metsenat-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - metsenat-db:/var/lib/postgresql/data 
    networks:
      - dev

networks:
  dev:
    driver: bridge

volumes:
  metsenat-db:
    driver: local
